### ISSUE TITLE
login across platforms

### ISSUE THREAD

**Issue by dcugh** [SAEONData/NCCRD#130]
https://app.asana.com/0/1111931073624690/1112152394465925

**Comment by andre-engelbrecht** [comment]
It took 2 days of trouble shooting to find the cause of this issue.

A while back I did some optimisation regarding the chunks/bundles generates by Webpack when you build the project. I spilt the project into multiple smaller chunks which supposedly should make page refreshes faster after site updates. This cause the silent-renew bundle to break because I did not include all the needed dependencies into that entry.

The issue is now resolved.

**Comment by andre-engelbrecht** [comment]
Linked to https://github.com/SAEONData/CCIS/issues/61
